//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
package code;
public class q2 
{
public static void main(String args[])
 {
 int a=1,b=2,s=2,c=0;
while(c<4000000)
{
 c=a+b;
 if(c%2==0)
 {   s=s+c;
  }
a=b;
  b=c;
}
  System.out.println(s);
}
} 

//output
//4613732
